FROM python:3.8-slim-buster

# Set environment variables
ENV FLASK_APP=flaskr
ENV FLASK_ENV=development
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000

# Create and set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Initialize the database
RUN flask init-db

# Expose port 5000
EXPOSE 5000

# Run the application
CMD ["flask", "run"]
