version: '3.1'

services:

  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: DAT515
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1414
    ports:
      - 5432:5432

  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1414
      MYSQL_DATABASE: DAT515
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres_db
      - mysql_db
    ports:
      - 8080:8080

  blog:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000