apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: mysqldb
  labels:
    app: mysqldb
spec:
  # Choose how to expose your service
  #type: NodePort
  ports:
    # The port number to expose the service
    - protocol: TCP
      port: 3306
      targetPort: 3306
  # Pod to route service traffic  
  selector:
    app: mysqldb
