version: '3.1'

services:

  postgres_db:
    image: postgres:14-bullseye
    restart: always
    environment:
      POSTGRES_DB: DAT515
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  #mysql_db:
  #  build:
  #    context: ./db
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #  ports:
  #    - 3336:3306
  #  volumes:
  #    - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres_db
      - mysql_db
    ports:
      - 8080:8080

  blog:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres_db
    ports:
      - 5000:5000
    command: flask run