version: '3.1'

services:

  postgres_db:
    image: postgres:14-bullseye
    restart: always
    environment:
      POSTGRES_DB: DAT515
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres_db
    ports:
      - 8080:8080

  blog:
    image: jesper14/blog:v1
    restart: always
    depends_on:
      - postgres_db
    ports:
      - 5000:5000
    command: flask run
