# Other python images did not work, due to lack of gcc
FROM python:3.8-slim-buster

# Create working directory within image
WORKDIR /app

# Copy local files into image's /app directory
COPY . /app

# Install requirements 
RUN pip3 install -r requirements.txt

# Expose a port 
EXPOSE 5000

# Run the app
CMD python ./main.py
